"""
Django settings for pr_eni project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY") or get_random_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = []
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
DEBUG = os.environ.get(
    'DEBUG',
    'False' if RENDER_EXTERNAL_HOSTNAME else 'True',
) == 'True'
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append (RENDER_EXTERNAL_HOSTNAME)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app_autenticacion',
    'app_convocatorias',
    'app_inscripciones',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pr_eni.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pr_eni.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",conn_max_age=600, ssl_require=not DEBUG)
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
if not DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

if not DEBUG:
    supabase_storage_settings = {
        'SUPABASE_STORAGE_BUCKET': os.environ.get('SUPABASE_STORAGE_BUCKET'),
        'SUPABASE_S3_ENDPOINT': os.environ.get('SUPABASE_S3_ENDPOINT'),
        'SUPABASE_S3_REGION': os.environ.get('SUPABASE_S3_REGION'),
        'SUPABASE_S3_ACCESS_KEY_ID': os.environ.get('SUPABASE_S3_ACCESS_KEY_ID'),
        'SUPABASE_S3_SECRET_ACCESS_KEY': os.environ.get(
            'SUPABASE_S3_SECRET_ACCESS_KEY',
        ),
    }
    missing_supabase_settings = [
        name for name, value in supabase_storage_settings.items() if not value
    ]
    if missing_supabase_settings:
        raise ImproperlyConfigured(
            'Faltan variables de Supabase Storage: '
            + ', '.join(missing_supabase_settings),
        )

    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3.S3Storage',
            'OPTIONS': {
                'access_key': supabase_storage_settings[
                    'SUPABASE_S3_ACCESS_KEY_ID'
                ],
                'secret_key': supabase_storage_settings[
                    'SUPABASE_S3_SECRET_ACCESS_KEY'
                ],
                'bucket_name': supabase_storage_settings[
                    'SUPABASE_STORAGE_BUCKET'
                ],
                'endpoint_url': supabase_storage_settings[
                    'SUPABASE_S3_ENDPOINT'
                ],
                'region_name': supabase_storage_settings['SUPABASE_S3_REGION'],
                'signature_version': 's3v4',
                'addressing_style': 'path',
                'default_acl': None,
                'querystring_auth': True,
                'querystring_expire': 600,
                'file_overwrite': False,
            },
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
